# Generated by Django 5.1.1 on 2024-09-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REGULAR", "Regular"),
                            ("COS", "Contract of Service"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
